# Generated by Django 2.1.5 on 2019-01-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterForBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('nomeProjeto', models.TextField(blank=True, default='', null=True)),
                ('tituloProjeto', models.TextField(blank=True, default='', null=True)),
                ('descricaoProjeto', models.TextField(blank=True, default='', null=True)),
                ('iconeProjeto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('login_redirect_url', models.CharField(max_length=250, blank=True, null=True, default='/core/')),
                ('login_url', models.CharField(max_length=250, blank=True, null=True, default='/core/login/')),
                ('logout_redirect_url', models.CharField(max_length=250, blank=True, null=True, default='/core/login/')),
            ],
            options={
                'verbose_name': 'Parametro para o Core',
                'verbose_name_plural': 'Parametros para o Core',
            },
        ),
    ]
