# Generated by Django 2.1.5 on 2019-02-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190211_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametersUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('senha_padrao', models.CharField(default='password@123456', help_text='Senha padrão que sera criada quando resetar senha do usuario', max_length=30, verbose_name='Senha padrão para reset')),
            ],
            options={
                'verbose_name': 'Parâmetro do Usuário',
                'verbose_name_plural': 'Parâmetros dos Usuários',
                'permissions': (('can_reset_password', 'Pode resetar a senha'),),
            },
        ),
    ]
