# Generated by Django 2.1.4 on 2019-01-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parameterforbase_url_integracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariobase',
            name='prodata',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
