# Generated by Django 2.1.7 on 2019-03-27 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20190211_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente_string', models.CharField(blank=True, max_length=60, null=True, verbose_name='Remetente Descrição')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('url', models.CharField(max_length=60, verbose_name='View name URL')),
                ('parametro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Parametro URL')),
                ('parametro_get', models.CharField(blank=True, max_length=60, null=True, verbose_name='Parametro GET')),
                ('visualizado', models.BooleanField(db_index=True, default=False, verbose_name='Visualizado')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('tipo', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10, verbose_name='Tipo')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificationbase_destinatario', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('remetente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificationbase_remetente', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-data_envio'],
            },
        ),
    ]
